# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [2]:
a = np.zeros((1, 10))
print(a)
a.size

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


10

#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [3]:
a= np.zeros((1,10))
a[0, 4]=1
print(a)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [4]:
b= np.arange(10, 50, 1)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [5]:
c = b[::-1]
print(c)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [6]:
d = np.arange(0,9,1)
e = d.reshape(3,3)
print(e)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


####7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [7]:
f = np.array([1,2,0,0,4,0])
f > 0 

array([ True,  True, False, False,  True, False])

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [8]:
np.random.randint(0,8 ,size=(3,3,3))

array([[[0, 2, 7],
        [2, 7, 3],
        [4, 1, 6]],

       [[2, 1, 2],
        [1, 2, 6],
        [6, 0, 3]],

       [[3, 6, 0],
        [5, 2, 1],
        [3, 6, 0]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [9]:
np.random.randint(0,8, size=(10,10))

array([[1, 0, 4, 0, 6, 0, 2, 4, 6, 7],
       [3, 6, 2, 3, 3, 4, 1, 4, 2, 2],
       [7, 0, 1, 2, 1, 6, 5, 1, 4, 4],
       [3, 5, 1, 1, 3, 6, 0, 1, 0, 3],
       [2, 3, 3, 0, 1, 4, 7, 7, 4, 0],
       [6, 7, 3, 1, 1, 6, 3, 4, 5, 2],
       [1, 7, 3, 3, 0, 6, 3, 6, 6, 0],
       [2, 3, 6, 3, 3, 5, 0, 1, 6, 5],
       [7, 6, 4, 3, 0, 6, 6, 6, 5, 0],
       [1, 1, 7, 7, 4, 6, 1, 3, 7, 2]])

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [10]:
g = np.random.randint(0,15, size=(30))
print(g)
h = sum(g)
print(h)
print (h/g.size)

[ 2 14 10 12  5  8  4  7  1 13 13 11  5 11 13  8  0  0  8  3  3  4  3 12
 13  1 14 11  5  8]
222
7.4


#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [11]:
i = np.ones((3,3))
i[1,1]=0
print(i)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [12]:
j = np.zeros((5,5))
print(j)
print(i)
j[1:-1,1:-1] = i
print(j)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
nan
False
False
nan
True
False

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [27]:
k = np.zeros((5,5))
k[[1,2,3,4],[0,1,2,3]]= [1,2,3,4]
print(k)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [97]:
l = np.random.randint(0,337,size=(5,6,7))
z=(100//(6*7))
x=((100%(6*7))%6)-1
y=((100%(6*7))%7)-1
print(z)
print(x)
print(y)
print(l)

l[z][y][x]


2
3
1
[[[115 288 241 306  61 143 141]
  [187  92 294 283 115  78 303]
  [300 210  17 181   7 271  13]
  [ 59 310 121 310 130 109  53]
  [106  20 276 289  92 213 157]
  [183 222 124 214  12  13  18]]

 [[  0 267 129  84 123  56 220]
  [154 230  37 282 103 114 179]
  [ 47 201 311  69 304 258 114]
  [252  43  32 255  82  95 160]
  [154 256  19 208 173   4 161]
  [334 257 114  66 234 307 239]]

 [[241 205 285 246 315  25  77]
  [101  87  93  30 224 124  10]
  [216  26 297 119 146  72  83]
  [198 263  78 232 251 247  70]
  [ 38 216 289  42  20 204 114]
  [ 43 195 215 292 277 329  21]]

 [[310  10  41 202  40 117 135]
  [ 53 332 162 103 175 175 140]
  [289 171 134 141 294  91  66]
  [298  82  55  78  56 312 278]
  [284 140 115  13 102 227   8]
  [ 56 170 261  90 146 145 127]]

 [[317 238 250 297 229 298 144]
  [133 301   0 286 293 224 326]
  [167  67 325 283 233  44 239]
  [218 149 325 156  61 220  43]
  [ 98 213 290  90 150 266 226]
  [336 143 199 164 312 180 198]]]


30

#### 16. Normalize a 5x5 random matrix (★☆☆)

In [48]:
m = np.random.randint(0,8, size = (5,5))
norm_m = np.linalg.norm(m)
normal_m= m/norm_m
print(normal_m)


[[0.12958026 0.17277369 0.30235395 0.30235395 0.12958026]
 [0.30235395 0.21596711 0.12958026 0.         0.12958026]
 [0.         0.17277369 0.12958026 0.21596711 0.        ]
 [0.21596711 0.12958026 0.08638684 0.17277369 0.25916053]
 [0.30235395 0.30235395 0.30235395 0.12958026 0.17277369]]


#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [58]:
n = np.random.randint(0,15, size = (12))
o = n[n<3]
p = n[n>8]
np.concatenate([o, p])

array([ 2, 14,  9, 11, 10])

#### 18. How to round away from zero a float array ? (★☆☆)

In [16]:
q = np.random.random_sample(15)

print(np.round(q))

[0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0.]


#### 19. Find common values between two arrays? (★☆☆)

In [25]:
r = np.random.randint(0,10, size=(15))
s = np.random.randint(0,10, size=(15))
print (np.intersect1d(r, s))
print (r)
print (s)

[1 2 3 5 6 8 9]
[5 0 5 9 9 1 1 0 9 8 2 2 3 1 6]
[8 9 7 2 5 1 3 1 6 6 6 9 3 6 6]


#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [5]:
def generator():
    x = np.random.randint(0,10, size =10)
    return x

generator()

array([3, 7, 2, 4, 7, 2, 8, 1, 3, 6])

#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [31]:
t = np.random.rand(10)
print(t)

[0.8144543  0.15144214 0.49674547 0.74150341 0.565694   0.92070833
 0.53475574 0.70392415 0.8750035  0.6598532 ]


#### 23. Create a random vector of size 10 and sort it (★★☆)

In [4]:
u = np.random.rand(10)
np.sort(u)

array([0.06597745, 0.33130372, 0.4902509 , 0.53421048, 0.64805922,
       0.79077647, 0.79698497, 0.84205581, 0.90871192, 0.9995286 ])

#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [30]:
Array_A = np.random.randint(0,4, size=5)
Array_B = np.random.randint(0,4, size=5)
np.array_equal(Array_A, Array_B) 

False

#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [6]:
Random_Vector = np.random.randint(0,20, size=10)
print(Random_Vector)
Max = Random_Vector.max(axis=0)
print(Max)
np.place(Random_Vector, Random_Vector== Max, [0])
print(Random_Vector)


[ 8 14  9  7  9  9 16  8  2  0]
16
[ 8 14  9  7  9  9  0  8  2  0]


#### 26. Find the closest value to random element in a vector? (★★☆)

In [54]:
Random_Vector2 = np.random.randint(0,50, size=10)
print(Random_Vector2)
x=5
index = (np.abs(x-Random_Vector2)).argmin()
print(Random_Vector2[index])


[ 3 43 11  7  0 16 13 23 32  8]
3


#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [29]:
Float_A = np.array([3.5, 5.6, 7.8, 2.4 ])
print(Float_A)
Int_A = Float_A.astype(int)
print(Int_A)

[3.5 5.6 7.8 2.4]
[3 5 7 2]


#### 28. Sort an array by the nth column? (★★☆)

In [42]:
Nth_array = np.random.randint(0,8, size = (5,5))
n=2
Sortn = Nth_array[Nth_array[:, n].argsort()]
print(Sortn)

[[0 4 0 4 4]
 [5 1 0 1 3]
 [1 7 1 4 7]
 [5 7 6 6 6]
 [2 2 6 2 3]]


#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

In [8]:
Float_2D = np.random.random_sample(20)
Float_2D == np.NaN

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [71]:
Vector = np.array([1, 2, 3, 4, 5])
NewVector = np.insert(Vector, 1, (0,0,0))
NewVector = np.insert(NewVector, 5, (0,0,0))
NewVector = np.insert(NewVector, 9, (0,0,0))
NewVector = np.insert(NewVector, -1, (0,0,0))
print(NewVector)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


## 31. Swap two rows of an array? (★★★)

In [ ]:
swap_array = np.random.randint(0,8, size = (5,5))
print(swap_array)
swap_array[[0, 2]] = swap_array[[2, 0]]
print(swap_array)

[[0 7 2 7 3]
 [7 6 1 2 5]
 [0 6 4 2 2]
 [5 0 6 2 0]
 [7 6 2 3 3]]
[[0 6 4 2 2]
 [7 6 1 2 5]
 [0 7 2 7 3]
 [5 0 6 2 0]
 [7 6 2 3 3]]


#### 32. How to negate a boolean value inside an array? (★★★)

In [74]:
Boolean_array = np.array([ 4 , 5 ,6, 3,2, 5,6,7,3,2, False, 65,4,3,8,])
print(np.logical_not(Boolean_array, out=Boolean_array))
print(Boolean_array)


[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]


#### 33. Find the most frequent value in an array?

In [5]:
Freq_array = np.random.randint(0,8, size = (25))
print(Freq_array)
count = np.bincount(Freq_array).argmax()
print(count)


[7 2 4 0 0 4 1 4 6 7 2 0 7 4 2 0 1 3 6 3 6 1 4 7 5]
4


#### 34. Get the n largest values of an array (★★★)

In [7]:
Nlarge_array = np.random.randint(0,75, size = (25))
print(Nlarge_array)
largest = np.unique(np.sort(Nlarge_array))[-1]
print(largest)

[19 63 29 57 10 19 62 69 25 56 14 50 46 49 38 58 59 52  8 18 37 32  8 12
 55]
69


#### 35. Extract unique rows from a two dimensional array? (★★★)

In [6]:
Unique_array = np.random.randint(0,2, size = (8,3))
print(Unique_array)
end = np.unique(Unique_array, axis =0)
print(end)

[[0 1 0]
 [1 0 1]
 [0 1 0]
 [1 0 1]
 [0 0 1]
 [1 0 1]
 [0 1 1]
 [1 1 0]]
[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]
